### ISSUE TITLE
performance on validation set

### ISSUE THREAD

**Issue by ShoufaChen** [kbrodt/waymo-motion-prediction-2021#11]
Hi,

how to test the performance on validation split?

**Comment by kbrodt** [comment]
Hi, there is no script to test the performance. You may take [visualize.py](https://github.com/kbrodt/waymo-motion-prediction-2021/blob/main/visualize.py) and [submit.py](https://github.com/kbrodt/waymo-motion-prediction-2021/blob/main/submit.py) scripts to get the trajectories.

**Comment by ShoufaChen** [comment]
Hi, @kbrodt 
Thanks for your reply.

I noticed that you reported the performance on the validation set in the workshop report.

How did you get that result?

**Comment by kbrodt** [comment]
The competition platform allowed us to submit against validation.

**Comment by ShoufaChen** [comment]
Thanks for your help.

BTW, does testing against validation have times limit? E.g. 3 times within a month?

**Comment by ShoufaChen** [comment]
“You may submit against the Validation Set as many times as you like”
