### ISSUE TITLE
Question About the waymo dataset lane type

### ISSUE THREAD

**Issue by SwagJ** [kbrodt/waymo-motion-prediction-2021#13]
Hi, @kbrodt, 

Thank you for your great work. I am new to this area, so I have a question regarding to the lane type of waymo dataset. In general, the lanes in waymo dataset, can be broadly categorized into 6: lanecenters, roadlines, stopsign, speedbump, roadedge and crosswalks. So, is the lane centers are just the the center of each line in which the vehicles can drive on? Theoretically, a car's center should be on the lanecenters if this car is staying in this lane. Is my interpretation right? 
Also, is the lanecenters in waymo the same as the centerlines in Argoverse Dataset? Are you familiar with that dataset? 
I am looking forward to your reply. 
Thank you in advance.

**Comment by kbrodt** [comment]
Hi @SwagJ,
I think you are right. For simplicity we assume the car is parametrized with a point (center of mass) on centerline with some dimensions.
Sorry, I'm not familiar with Argoverse dataset.

**Comment by SwagJ** [comment]
Hi,

Thank you for your reply. 

Best,
