### ISSUE TITLE
After executing the visualize.py code nothing is saved in the folder

### ISSUE THREAD

**Issue by G-raghava** [kbrodt/waymo-motion-prediction-2021#17]
![visualization execution](https://user-images.githubusercontent.com/92630358/235218180-d771a925-86eb-4194-8588-7e09856b9e64.png)

Can Please resolve the issue. what was the error i am facing.

**Comment by kbrodt** [comment]
https://stackoverflow.com/questions/76028164/tensorflow-object-detection-tf-trt-warning-could-not-find-tensorrt

**Comment by G-raghava** [comment]
Hi Today also facing the same issue. can someone help me is there any process to do it.

![image](https://user-images.githubusercontent.com/92630358/235317775-cb108921-1e9e-4fa9-b402-93f0cd910ad1.png)

whatever the path is given for saving the folder it exists but the file is saved in the folder.

"/home/talapallysk/waymo-motion-prediction-2021/viz/xception71/" I have provided the path for the folder saved but no file is saved.   Please help me.

**Comment by G-raghava** [comment]
Please resolve the above issue
