### ISSUE TITLE
Weights of model

### ISSUE THREAD

**Issue by adeshkin** [kbrodt/waymo-motion-prediction-2021#2]
Thanks you for great work!
Can you share weights of best model?

**Comment by kbrodt** [comment]
Sure, you can find [here](https://github.com/kbrodt/waymo-motion-prediction-2021/releases/download/0.1/waymo_motion_prediction_orig.zip) the archive with dirty code and weights.

**Comment by adeshkin** [comment]
@kbrodt 
model - test_xception71_263000_dev_131.pth
Is it correct? 
`RuntimeError: Given groups=1, weight of size [32, 47, 3, 3], expected input[1, 25, 224, 224] to have 47 channels, but got 25 channels instead
`

**Comment by kbrodt** [comment]
You must use code inside zip archive
