### ISSUE TITLE
Angle conversion error at prerender.py 

### ISSUE THREAD

**Issue by KyuhwanYeon** [kbrodt/waymo-motion-prediction-2021#4]
Thank you for amazing works. 

I found the conversion error at prerender.py

https://github.com/kbrodt/waymo-motion-prediction-2021/blob/3665d4b3ba39a6b879b663747f93b6e525018c00/prerender.py#L706
https://github.com/kbrodt/waymo-motion-prediction-2021/blob/3665d4b3ba39a6b879b663747f93b6e525018c00/prerender.py#L707

These two lines has conversion error.

In order to  convert coordinate properly,  it should be changed like this
`tmp[3] = other_v_yaw - ANGLE`
`tmp[4] = other_bbox_yaw - ANGLE `

**Comment by kbrodt** [comment]
Hi,

Thanks for your help. I guess you are right.

Actually we didn't use this function and the features it produces for training process. It is only used for visualization.

**Comment by KyuhwanYeon** [comment]
Right, I also understand it doesn't affect to training accuracy, but if someone want to visualize with box, not point, the yaw angle is important. I was just trying to let you know.
anyway thanks to amazing works :)

**Comment by kbrodt** [comment]
Thanks for the fixes, Yeon!
