### ISSUE TITLE
Vehicles driving on the same lane

### ISSUE THREAD

**Issue by ghost** [kbrodt/waymo-motion-prediction-2021#5]
Hello!

Thanks for sharing you work!

I have one questions: from the motion dataset, is that possible to know if two vehicles are driving on the same lane? I notice that there is a column called "roadgraph_samples/id" but I am not sure whether that means the lane ID.

Thanks.

**Comment by kbrodt** [comment]
Hello,

See [here](https://waymo.com/open/data/motion/tfexample).

**Comment by ghost** [comment]
Thank you so much for your reply!

Actually I have found this after posting my issue. It seems this column is about the sample points. So it may not be useful if I need to extract car-following events from the motion dataset where one vehicle is driving right behind another vehicle on the same lane.
